@baseUrl = http://localhost:3000/api/task

get {{baseUrl}}

###

post {{baseUrl}}

{
    "name": "Pet Mouchan",
    "description": "He's a good kitty."
}

###
post {{baseUrl}}

{
    "name": "Learn Next gud"
}